ParaApp/ParaApp/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ParaApp.Areas.HelpPage.Models;

namespace ParaApp.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

ParaApp/ParaApp/Controllers/ItinerariesController.cs
using ParaApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ParaApp.Controllers
{
    public class ItinerariesController : Controller
    {
        //
        // GET: /Itineraries/


        //
        // GET: /Itineraries/Details/5

        public ActionResult Index()
        {
            List<Marker> Markers = new List<Marker>();
            using (ItineraryListContext db = new ItineraryListContext())
            {
                List<MyMarkers> myMarkers = new List<MyMarkers>();
                myMarkers = db.MyMarkers.Where(m=>m.UserName == User.Identity.Name).ToList();
                foreach (MyMarkers myMarker in myMarkers)
                {
                    try
                    {
                        Markers.Add(db.Marker.Single(m => myMarker.MarkerID == m.ID));
                    }
                    catch { }
                }
            }
            MarkersAndTemp mAndT = new MarkersAndTemp();
            mAndT.Markers = Markers;
            
            return View(mAndT);
        }

        //
        // GET: /Itineraries/Create

        public ActionResult Add(double latitude,double longitude,string caar)
        {
            
            using (ItineraryListContext db = new ItineraryListContext())
            {
                if (db.Temporary.Where(x=>x.UserName == User.Identity.Name) == null)
                {
                    db.Temporary.Add(new Temporary() {UserName=User.Identity.Name,Coordinates = String.Empty,Method=String.Empty});
                    db.SaveChanges();
                }
                Temporary temp = db.Temporary.Single(x => x.UserName == User.Identity.Name);
                if (temp.Coordinates.Length > 0) temp.Coordinates += ":";
                if (temp.Method.Length > 0) temp.Method += ":";
                temp.Coordinates += string.Format("{0},{1}", latitude, longitude);
                temp.Method += "car";
                db.SaveChanges();
            }

            return View();
        }

        //
        // POST: /Itineraries/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Itineraries/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Itineraries/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Itineraries/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Itineraries/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ParaApp/ParaApp/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ParaApp.Models;
using System.IO;
using Newtonsoft.Json;
using System.Text;

namespace ParaApp.Controllers
{
    public class PlacesController : Controller
    {
        //
        // GET: /Places/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddMarker(string lat, string lon, string vicinity,string title)
        {
            double latitude = double.Parse(lat);
            double longitude = double.Parse(lon);
            int markerid = new int();

            string result = "Successfully added to My Markers";
            using (ItineraryListContext db = new ItineraryListContext())
            {
                lock (db.Marker)
                {
                    List<Marker> markers = db.Marker.ToList();
                    if (!markers.Exists(m=>m.Latitude==latitude && m.Longitude == longitude && m.Vicinity == vicinity && m.Name == title))
                    {
                        db.Marker.Add(new Marker() { Latitude = latitude, Longitude = longitude, Vicinity = vicinity, Name = title });
                        db.SaveChanges();
                        markerid = db.Marker.Single(m=>m.Latitude==latitude && m.Longitude == longitude && m.Vicinity == vicinity && m.Name == title).ID;
                    }
                }
                lock (db.MyMarkers)
                {
                    List<MyMarkers> mymarkers = db.MyMarkers.ToList();
                    
                    if (!mymarkers.Exists(m=>m.UserName ==User.Identity.Name && m.MarkerID == markerid))
                    {
                        db.MyMarkers.Add(new MyMarkers() { UserName = User.Identity.Name, MarkerID = markerid });
                        db.SaveChanges();
                    }
                    else
                    {
                        result = "Marker already in My Markers";
                    }
                }
            }
            PlaceQuery pq = new PlaceQuery();
            string q = string.IsNullOrWhiteSpace(pq.Query) ? "restaurants" : pq.Query;
            string lat2 = string.IsNullOrWhiteSpace(pq.Latitude) ? "14.5500" : pq.Latitude;
            string lon2= string.IsNullOrWhiteSpace(pq.Longitude) ? "121.0333" : pq.Longitude;
            pq.Query = q;
            pq.Latitude = lat2;
            pq.Longitude = lon2;
            Places places;
            HttpWebRequest request = (HttpWebRequest)System.Net.WebRequest.Create(string.Format("http://places.demo.api.here.com/places/v1/discover/search?at={1}%2C{2}&q={0}&accept=application%2Fjson&app_id={3}&app_code={4}", q, lat, lon, "DemoAppId01082013GAL", "AJKnXv84fjrb0KIHawS0Tg"));
            using (Stream stream = request.GetResponse().GetResponseStream())
            using (StreamReader streamReader = new StreamReader(stream))
            {
                string json = streamReader.ReadToEnd();
                places = JsonConvert.DeserializeObject<Places>(json);
            }
            return View("Index", new ItemsAndQuery() { PlaceQuery = pq, ItemList = places.results.items.ToList(), Message = result });
        }
        //
        // GET: /Places/Details/5
        public ActionResult Places(PlaceQuery pq)
        {
            string q = string.IsNullOrWhiteSpace(pq.Query) ? "restaurants" : pq.Query ;
            string lat = string.IsNullOrWhiteSpace(pq.Latitude) ? "14.5500" : pq.Latitude;
            string lon = string.IsNullOrWhiteSpace(pq.Longitude) ? "121.0333" : pq.Longitude;
            pq.Query = q;
            pq.Latitude = lat;
            pq.Longitude = lon;
            Places places;
            HttpWebRequest request = (HttpWebRequest)System.Net.WebRequest.Create(string.Format("http://places.demo.api.here.com/places/v1/discover/search?at={1}%2C{2}&q={0}&accept=application%2Fjson&app_id={3}&app_code={4}", q, lat, lon, "DemoAppId01082013GAL", "AJKnXv84fjrb0KIHawS0Tg"));
            using (Stream stream = request.GetResponse().GetResponseStream())
            using (StreamReader streamReader = new StreamReader(stream))
            {
                string json = streamReader.ReadToEnd();
                places = JsonConvert.DeserializeObject<Places>(json);
            }
            return View("Index",new ItemsAndQuery(){PlaceQuery= pq, ItemList= places.results.items.ToList()});
        }
        //public ActionResult Places()
        //{
        //    string q = "restaurant";
        //    string lat = "14.5500";
        //    string lon = "121.0333";
        //    Places places;
        //    HttpWebRequest request = (HttpWebRequest)System.Net.WebRequest.Create(string.Format("http://places.demo.api.here.com/places/v1/discover/search?at={1}%2C{2}&q={0}&accept=application%2Fjson&app_id={3}&app_code={4}", q, lat, lon, "DemoAppId01082013GAL", "AJKnXv84fjrb0KIHawS0Tg"));
        //    using (Stream stream = request.GetResponse().GetResponseStream())
        //    using (StreamReader streamReader = new StreamReader(stream))
        //    {
        //        string json = streamReader.ReadToEnd();
        //        places = JsonConvert.DeserializeObject<Places>(json);
        //    }
        //    return View("Index",places.results.items.ToList());
        //}
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Places/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Places/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Places/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Places/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Places/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Places/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ParaApp/ParaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css"
          href="http://js.api.here.com/v3/3.0/mapsjs-ui.css" />
    <script type="text/javascript" charset="UTF-8"
            src="http://js.api.here.com/v3/3.0/mapsjs-core.js"></script>
    <script type="text/javascript" charset="UTF-8"
            src="http://js.api.here.com/v3/3.0/mapsjs-service.js"></script>
    <script type="text/javascript" charset="UTF-8"
            src="http://js.api.here.com/v3/3.0/mapsjs-mapevents.js"></script>
    <script type="text/javascript" charset="UTF-8"
            src="http://js.api.here.com/v3/3.0/mapsjs-ui.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <!-- load user-defined styles -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/paraapp")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/ajaxlogin")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Makati, Philippines</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#top">Top Itineraries</a></li>
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Search", "Places", "Places")</li>
                        <li>@Html.ActionLink("Create Itineraries", "Index","Itineraries")</li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    </div>
   
   
    <div id="userSettings">
        @Html.Partial("_UserSettings")
    </div>

    <div id="body">
        @RenderBody()
    </div>

    @*<footer>
        <nav>
            <ul id="menu">
                <li>@Html.ActionLink("Todo List", "Index", "Home", new { area = "" }, null)</li>
                <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>
            </ul>
        </nav> 
        <p>Learn more about <a href="http://go.microsoft.com/fwlink/?LinkId=273732">Single Page Applications</a></p>
        <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
    </footer>*@
</body>
</html>

ParaApp/ParaApp/Views/Shared/_UserSettings.cshtml
@if (Request.IsAuthenticated) {
    <text>
        Hello, @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: new { area = "" }, htmlAttributes: new { @class = "username", title = "Manage" })
        @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" })) {
            @Html.AntiForgeryToken()
            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
        }
    </text>
}